### ISSUE TITLE
Bytte ut SCSS med CSS

### ISSUE THREAD

**Issue by eliihen** [kartverket/kvib#13]
Jeg synes KVIB er et syvmilssteg i riktig retning for å standardisere designuttrykket til løsningene ved å lage design-primitiver, og all honnør til @nilben som tok lead på å få til dette :clap: 

## Forslag

En tanke jeg hadde som potensielt kunne gjort prosjektet hakket mer fremtidssikkert hadde vært å ta i bruk CSS-variabler istedenfor SCSS-variabler. Det ser ut som det stort sett er dette + includes som SCSS brukes til i dette biblioteket, og det er helt fair. Så om man bruker CSS-variabler får man stort sett den samme funksjonaliteten. 

![cssvar](https://user-images.githubusercontent.com/5845924/159947985-03cb1710-00a8-40f0-9238-00db43a5c2be.gif)

Fordelen med CSS-variabler over SCSS er:
- Lavere kompleksitet i det at man ikke trenger et kompilasjonssteg, mindre som kan gå galt
- Lowest common denominator. Hvem vet hva som er det neste kule som kommer til å erstatte SCSS, mens CSS er en del av plattformen
- Flere som kan CSS enn SCSS, mindre opplæring
- CSS-variabler kan endres i nettleseren runtime som gjør utvikling lettere og lar man endre mellom f.eks. light og dark mode
- Man kan scope variabler så f.eks. `--grid-m` er satt til `8px` på rot og `0px` innenfor tabeller
- Blir mer kompatibelt med shadow DOM og Web Components

Det går også ann å ta i bruk en mellomløsning hvor man bruker CSS-variabler men beholder SCSS for mixins.

## Eksempel

For eksempel kan følgende klasse:

```scss
.btn-primary {
  @include shared_button_styles;
  background-color: $groenn_moerk;
  border: none;
  color: white;
  padding: $grid-m $grid-l;

  &:visited {
    color: white;
  }
}
```

Skrives som:

```css
.btn-primary {
  background-color: var(--green-dark);
  border: none;
  color: white;
  padding: var(--grid-m) var(--grid-l);
}
.btn-primary:visited {
  color: white;
}
```

Det eneste man ikke får her er `@include`-funksjonen, men det kan løses med å si at man bruker `.btn .btn-primary` i HTML class istedenfor. 

En annen kul ting med dette er at man kan potensielt bruke CSS modules ut av boksen:

```js
import { btnPrimary } from '@kartverket/kvib';

export Button = ({ children }) => (
  <button className={btnPrimary}>
    {children}
  </button>
);
```
